device:
  # ADB server 的端口。部分模拟器为避免冲突可能会将 ADB server 开在其他端口，
  # 此时可以更改此设置以利用模拟器自带的 ADB server。
  # adb_server: 127.0.0.1:5037

  # 需要启动 adb server 时，使用的 adb 命令
  # 为空时则尝试: 1. PATH 中的 adb；
  #               2. ADB/{sys.platform}/adb;
  #               3. 查找 Android SDK（ANDROID_SDK_ROOT 和默认安装目录）
  adb_binary:
  # 以下为部分模拟器提供的 adb 程序，不一定正确，仅供参考
  # adb_binary: D:\leidian\LDPlayer\adb.exe             # 雷电模拟器
  # adb_binary: C:\Program Files\BlueStacks\HD-Adb.exe  # BlueStacks
  # adb_binary: C:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe  # MuMu模拟器

  # 始终选择指定设备进行操作（指定 adb devices 中列出的名称）
  # adb_always_use_device:

  # 无设备连接时，自动 adb connect 此端口
  adb_auto_connect: 127.0.0.1:5555  # 大部分模拟器
  # adb_auto_connect: 127.0.0.1:7555  # MuMu模拟器

  # 使用兼容性较好（但较慢）的截图方式
  compat_screenshot: false

  # 模拟器内可访问本机端口时，尝试使用模拟器优化模式，加速截图数据传输
  # 模拟器判断逻辑：1. 设备名称以 "emulator-" 或 "127.0.0.1:" 开头
  #                 2. ro.product.board 包含 goldfish（SDK emulator）或存在 vboxguest 模块
  # PS. 部分模拟器（如 BlueStacks）无需此项优化，此项优化也可能会减慢截图速度
  try_emulator_enhanced_mode: true

  # 截图缓存：如果两次截图间隔小于上次截图耗时，则直接返回上次的截图
  cache_screenshot: true

  package_name: com.hypergryph.arknights
  # package_name: com.hypergryph.arknights.bilibili
  activity_name: com.u8.sdk.U8UnityContext

ocr:
  # 选择 OCR 引擎，非必要
  # 设置为 auto 则选择下列第一个可用的引擎: tesseract, windows_media_ocr, baidu
  engine: auto

  # 百度 API 设置，使用 baidu OCR 时需要正确填写
  baidu_api:
    # 是否将百度 OCR 标记为可用
    enabled: false
    # 百度 API 鉴权数据
    app_id: STUB
    app_key: STUB
    app_secret: STUB

reporting:
  # 是否将关卡掉落上传到企鹅数据 (penguin-stats.io)
  enabled: false

  # 企鹅数据的用户 ID
  # > 用户 ID 仅用来标记您的上传身份。在不同设备上使用此 ID 登录，可让掉落数据集中于一个账号下，方便管理上传以及查看个人掉落数据。
  # 如果为 null 或空，则在下一次上传时创建并更新到文件中
  penguin_stats_uid:

behavior:
  # 理智不足时自动使用理智回复道具
  # 免责声明：可能存在识别错误导致碎石，开发者对此不负任何责任
  refill_ap_with_item: false

  # 理智不足时自动碎石
  # 如需使用，请将大写字母改为小写
  REFILL_AP_WITH_ORIGINIUM: false

  # 代理指挥出现失误的处理
  mistaken_delegation:
    # 是否以 2 星结算关卡
    settle: false
    # 结算/放弃后，是否跳过失误关卡
    skip: true
