name: Windows binary package

on:
  push:
    branches: [ master ]

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9 amd64
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv64
        venv64\Scripts\python -m pip install --upgrade pip wheel setuptools
        venv64\Scripts\python -m pip install -r requirements.txt
        venv64\Scripts\python -m pip install pyinstaller pythonnet
      shell: cmd
    - name: Make package
      shell: cmd
      run: |
        venv64\Scripts\python packaging/makepackage.py --version-suffix -ci-%GITHUB_RUN_NUMBER%
    - name: Upload artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: akhelper-cp39-win_amd64
        path: dist/akhelper.zip
